import "./Window.css";
import Aplications from "../components/aplication/Aplication";
import Header from "../components/HeaderNav/Header";
import UseState from "../components/Context/UseContext";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <main className="app">
          <section className="app__background">
            <div className="app__background__window">
              <span className="app__background__window__span"></span>
              <span className="app__background__window__span"></span>
              <span className="app__background__window__span"></span>
              <span className="app__background__window__span"></span>
            </div>
          </section>
          <UseState>
            <Aplications />
            {children}
            <Header />
          </UseState>
        </main>
      </body>
    </html>
  );
}
