import MainNav from "../components/main/Main"

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <MainNav>
          {children}
        </MainNav>
      </body>
    </html>
  );
}
